require('base')
require('maps')
require('color')
require('plugins')
require('lsp')
require('plugins.cmp')
require('plugins.kind')
-- I think it's not already used
--require('p-snip')
require('plugins.treesitter')
require('plugins.telescope')
require('plugins.alpha')
require('plugins.lualine')
require('plugins.bufferline')
require('plugins.mason')
require('plugins.sniprun')
require('plugins.todo-comments')
require('other')
