-- base setting
require('base')
require('maps')
require('color')
require('plugins')
require('lsp')

-- plugins setting
require('plugins.cmp')
require('plugins.kind')
require('plugins.treesitter')
require('plugins.telescope')
require('plugins.alpha')
require('plugins.lualine')
require('plugins.bufferline')
require('plugins.mason')
require('plugins.sniprun')
require('plugins.todo-comments')
require('plugins.nvimtree')
require('plugins.bookmarks')
require('plugins.toggleterm')
require('other')
